version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: webiny/webiny-js:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
  - base: next
    upstream: webiny/webiny-js:next      # Required. Can be a branch in the same forked repo.
    assignees:              # Optional
      - graeme-asher
    reviewers:              # Optional
      - graeme-asher
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - graeme-asher
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict